# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: trakt-randomizer-scheduler

on:
  schedule:
  - cron: "*/180 * * * *" # runs every 3 hours
  workflow_dispatch:  

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        cache: 'pip' # caching pip dependencies
        
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi     
        
    - name: Run main.py
      env:
        AUTHORIZATION_TOKEN: ${{ secrets.AUTHORIZATION_TOKEN }}
        TRAKT_APP_API_ID: ${{ secrets.TRAKT_APP_API_ID }}
        TRAKT_APP_API_SECRET: ${{ secrets.TRAKT_APP_API_SECRET }}
        TRAKT_APP_ID: ${{ secrets.TRAKT_APP_ID }}
        URL_LIST: ${{ secrets.URL_LIST }}        
      run: |
        python main.py
